/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Advocate;

import Database.DatabaseCredentials;
import java.sql.Statement;
import java.sql.Connection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import Colour.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author parve
 */
public class MainDashboard extends javax.swing.JFrame {

    /**
     * Creates new form phase1
     */
    LoginPage object = new LoginPage();
    DatabaseCredentials dbc_1 = new DatabaseCredentials();
    String databaseUrl = dbc_1.getDatabaseUrl();
    String AdminPassword = "123456";
    Connection connection = null;
   Statement st = null;
    PreparedStatement pst = null;
   
    ResultSet result = null;

    
    
    Color defaultColor, clickedColor, white;
    color colorObject = new color();

    public MainDashboard() {
        initComponents();
        this.tab_container.setEnabledAt(7, false);
        this.nestedTabbedCase.setEnabledAt(0, true);

        defaultColor = new Color(255, 204, 0);
        clickedColor = new Color(51, 51, 51);
        white = new Color(255, 255, 255);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_container = new javax.swing.JPanel();
        header_container = new javax.swing.JPanel();
        software_name = new javax.swing.JLabel();
        user_name = new javax.swing.JLabel();
        logOut_button = new javax.swing.JButton();
        menu_container = new javax.swing.JPanel();
        Panel_dashbord_menu = new javax.swing.JPanel();
        label_dashboard_menu = new javax.swing.JLabel();
        Panel_AddressBook_menu = new javax.swing.JPanel();
        label_addressBook_menu = new javax.swing.JLabel();
        Panel_Appointment_menu = new javax.swing.JPanel();
        label_appointment_menu = new javax.swing.JLabel();
        Panel_toDoList_menu = new javax.swing.JPanel();
        label_todoList_menu = new javax.swing.JLabel();
        Panel_caseFolder_menu = new javax.swing.JPanel();
        label_caseFolder_menu = new javax.swing.JLabel();
        Panel_account_menu = new javax.swing.JPanel();
        label_account_menu = new javax.swing.JLabel();
        Panel_communication_menu = new javax.swing.JPanel();
        label_communication_menu = new javax.swing.JLabel();
        Panel_setting_menu = new javax.swing.JPanel();
        label_settings_menu = new javax.swing.JLabel();
        tab_container = new javax.swing.JTabbedPane();
        tab_dashboard = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        storedUserLabel = new javax.swing.JLabel();
        tab_address_book = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tab_appointment = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tab_todoList = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tab_caseFolder = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        nestedTabbedCase = new javax.swing.JTabbedPane();
        nestedCaseMenuBar = new javax.swing.JPanel();
        openNewCaseRadioBtn = new javax.swing.JRadioButton();
        MyFolderRadioBtn = new javax.swing.JRadioButton();
        activeFolderRadioBtn = new javax.swing.JRadioButton();
        openNewCaseJpanel = new javax.swing.JPanel();
        backJlabel = new javax.swing.JLabel();
        clientIdjLabel = new javax.swing.JLabel();
        clientIdTextField = new javax.swing.JTextField();
        categoryjLabel = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        caseworkerjLabel = new javax.swing.JLabel();
        caseWorkerTextField = new javax.swing.JTextField();
        introjLabel = new javax.swing.JLabel();
        introTextField = new javax.swing.JTextField();
        caseLocjLabel = new javax.swing.JLabel();
        caseLocTextField = new javax.swing.JTextField();
        openingDatejLabel = new javax.swing.JLabel();
        openingDateTextField = new javax.swing.JTextField();
        paymentjLabel = new javax.swing.JLabel();
        paymentTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        openingDateChooser = new com.toedter.calendar.JDateChooser();
        tab_accounts = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tab_communication = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tab_settings = new javax.swing.JPanel();
        ScrollPane_user_list = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchBox_userName = new javax.swing.JTextField();
        title_searchBox_userName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        main_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_container.setBackground(new java.awt.Color(0, 0, 0));

        software_name.setForeground(new java.awt.Color(255, 255, 255));
        software_name.setText("CASIAC");

        user_name.setBackground(new java.awt.Color(255, 255, 255));
        user_name.setForeground(new java.awt.Color(255, 255, 255));
        user_name.setText("SUPER ADMIN");

        logOut_button.setText("LOG OUT");
        logOut_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header_containerLayout = new javax.swing.GroupLayout(header_container);
        header_container.setLayout(header_containerLayout);
        header_containerLayout.setHorizontalGroup(
            header_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(software_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 664, Short.MAX_VALUE)
                .addComponent(user_name)
                .addGap(18, 18, 18)
                .addComponent(logOut_button)
                .addContainerGap())
        );
        header_containerLayout.setVerticalGroup(
            header_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(software_name)
                    .addComponent(user_name)
                    .addComponent(logOut_button))
                .addGap(445, 445, 445))
        );

        main_container.add(header_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 60));

        menu_container.setBackground(new java.awt.Color(255, 255, 102));

        Panel_dashbord_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_dashboard_menu.setBackground(new java.awt.Color(255, 255, 102));
        label_dashboard_menu.setText("Dashboard");
        label_dashboard_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_dashboard_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_dashboard_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_dashboard_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_dashbord_menuLayout = new javax.swing.GroupLayout(Panel_dashbord_menu);
        Panel_dashbord_menu.setLayout(Panel_dashbord_menuLayout);
        Panel_dashbord_menuLayout.setHorizontalGroup(
            Panel_dashbord_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dashbord_menuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label_dashboard_menu)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        Panel_dashbord_menuLayout.setVerticalGroup(
            Panel_dashbord_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dashbord_menuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label_dashboard_menu)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Panel_AddressBook_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_addressBook_menu.setText("Address Book");
        label_addressBook_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_addressBook_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_addressBook_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_addressBook_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_AddressBook_menuLayout = new javax.swing.GroupLayout(Panel_AddressBook_menu);
        Panel_AddressBook_menu.setLayout(Panel_AddressBook_menuLayout);
        Panel_AddressBook_menuLayout.setHorizontalGroup(
            Panel_AddressBook_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_AddressBook_menuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label_addressBook_menu)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        Panel_AddressBook_menuLayout.setVerticalGroup(
            Panel_AddressBook_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AddressBook_menuLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(label_addressBook_menu)
                .addContainerGap())
        );

        Panel_Appointment_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_appointment_menu.setText("Appointment");
        label_appointment_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_appointment_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_appointment_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_appointment_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_Appointment_menuLayout = new javax.swing.GroupLayout(Panel_Appointment_menu);
        Panel_Appointment_menu.setLayout(Panel_Appointment_menuLayout);
        Panel_Appointment_menuLayout.setHorizontalGroup(
            Panel_Appointment_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Appointment_menuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_appointment_menu)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        Panel_Appointment_menuLayout.setVerticalGroup(
            Panel_Appointment_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Appointment_menuLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(label_appointment_menu)
                .addContainerGap())
        );

        Panel_toDoList_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_todoList_menu.setText("To Do List");
        label_todoList_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_todoList_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_todoList_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_todoList_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_toDoList_menuLayout = new javax.swing.GroupLayout(Panel_toDoList_menu);
        Panel_toDoList_menu.setLayout(Panel_toDoList_menuLayout);
        Panel_toDoList_menuLayout.setHorizontalGroup(
            Panel_toDoList_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_toDoList_menuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label_todoList_menu)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        Panel_toDoList_menuLayout.setVerticalGroup(
            Panel_toDoList_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_toDoList_menuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label_todoList_menu)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Panel_caseFolder_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_caseFolder_menu.setText("Case Folders");
        label_caseFolder_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_caseFolder_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_caseFolder_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_caseFolder_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_caseFolder_menuLayout = new javax.swing.GroupLayout(Panel_caseFolder_menu);
        Panel_caseFolder_menu.setLayout(Panel_caseFolder_menuLayout);
        Panel_caseFolder_menuLayout.setHorizontalGroup(
            Panel_caseFolder_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_caseFolder_menuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_caseFolder_menu)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        Panel_caseFolder_menuLayout.setVerticalGroup(
            Panel_caseFolder_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_caseFolder_menuLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(label_caseFolder_menu)
                .addGap(34, 34, 34))
        );

        Panel_account_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_account_menu.setText("Accounts");
        label_account_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_account_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_account_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_account_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_account_menuLayout = new javax.swing.GroupLayout(Panel_account_menu);
        Panel_account_menu.setLayout(Panel_account_menuLayout);
        Panel_account_menuLayout.setHorizontalGroup(
            Panel_account_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_account_menuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label_account_menu)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        Panel_account_menuLayout.setVerticalGroup(
            Panel_account_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_account_menuLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(label_account_menu)
                .addContainerGap())
        );

        Panel_communication_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_communication_menu.setText("Communication");
        label_communication_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_communication_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_communication_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_communication_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_communication_menuLayout = new javax.swing.GroupLayout(Panel_communication_menu);
        Panel_communication_menu.setLayout(Panel_communication_menuLayout);
        Panel_communication_menuLayout.setHorizontalGroup(
            Panel_communication_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_communication_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_communication_menu)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        Panel_communication_menuLayout.setVerticalGroup(
            Panel_communication_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_communication_menuLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(label_communication_menu)
                .addContainerGap())
        );

        Panel_setting_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_settings_menu.setText("Settings");
        label_settings_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_settings_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_settings_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_settings_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_setting_menuLayout = new javax.swing.GroupLayout(Panel_setting_menu);
        Panel_setting_menu.setLayout(Panel_setting_menuLayout);
        Panel_setting_menuLayout.setHorizontalGroup(
            Panel_setting_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_setting_menuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_settings_menu)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        Panel_setting_menuLayout.setVerticalGroup(
            Panel_setting_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_setting_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_settings_menu)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menu_containerLayout = new javax.swing.GroupLayout(menu_container);
        menu_container.setLayout(menu_containerLayout);
        menu_containerLayout.setHorizontalGroup(
            menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Panel_dashbord_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_AddressBook_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_Appointment_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_toDoList_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_caseFolder_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Panel_communication_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Panel_setting_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu_containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_account_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        menu_containerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Panel_AddressBook_menu, Panel_Appointment_menu, Panel_communication_menu, Panel_dashbord_menu, Panel_toDoList_menu});

        menu_containerLayout.setVerticalGroup(
            menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_dashbord_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_AddressBook_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Appointment_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_toDoList_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_caseFolder_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(Panel_communication_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_setting_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_containerLayout.createSequentialGroup()
                    .addContainerGap(292, Short.MAX_VALUE)
                    .addComponent(Panel_account_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(142, 142, 142)))
        );

        menu_containerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Panel_AddressBook_menu, Panel_Appointment_menu, Panel_communication_menu, Panel_dashbord_menu, Panel_toDoList_menu});

        main_container.add(menu_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, 470));

        tab_dashboard.setBackground(new java.awt.Color(102, 255, 255));

        jPanel21.setBackground(new java.awt.Color(102, 102, 102));

        storedUserLabel.setBackground(new java.awt.Color(102, 102, 102));
        storedUserLabel.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        storedUserLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(storedUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(storedUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tab_dashboardLayout = new javax.swing.GroupLayout(tab_dashboard);
        tab_dashboard.setLayout(tab_dashboardLayout);
        tab_dashboardLayout.setHorizontalGroup(
            tab_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_dashboardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(555, Short.MAX_VALUE))
        );
        tab_dashboardLayout.setVerticalGroup(
            tab_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        tab_container.addTab("tab1", tab_dashboard);

        tab_address_book.setBackground(new java.awt.Color(204, 0, 102));

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout tab_address_bookLayout = new javax.swing.GroupLayout(tab_address_book);
        tab_address_book.setLayout(tab_address_bookLayout);
        tab_address_bookLayout.setHorizontalGroup(
            tab_address_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_address_bookLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel6)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        tab_address_bookLayout.setVerticalGroup(
            tab_address_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_address_bookLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel6)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tab_container.addTab("tab3", tab_address_book);

        tab_appointment.setBackground(new java.awt.Color(102, 255, 204));

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout tab_appointmentLayout = new javax.swing.GroupLayout(tab_appointment);
        tab_appointment.setLayout(tab_appointmentLayout);
        tab_appointmentLayout.setHorizontalGroup(
            tab_appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_appointmentLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel5)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        tab_appointmentLayout.setVerticalGroup(
            tab_appointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_appointmentLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel5)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        tab_container.addTab("tab2", tab_appointment);

        tab_todoList.setBackground(new java.awt.Color(204, 204, 0));

        jLabel14.setText("jLabel6");

        javax.swing.GroupLayout tab_todoListLayout = new javax.swing.GroupLayout(tab_todoList);
        tab_todoList.setLayout(tab_todoListLayout);
        tab_todoListLayout.setHorizontalGroup(
            tab_todoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_todoListLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel14)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        tab_todoListLayout.setVerticalGroup(
            tab_todoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_todoListLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel14)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tab_container.addTab("tab3", tab_todoList);

        tab_caseFolder.setBackground(new java.awt.Color(0, 51, 51));

        jLabel15.setText("jLabel6");

        nestedTabbedCase.setEnabled(false);

        openNewCaseRadioBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        openNewCaseRadioBtn.setText("Open New Case ");
        openNewCaseRadioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openNewCaseRadioBtnMouseClicked(evt);
            }
        });

        MyFolderRadioBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MyFolderRadioBtn.setText("My Folder");
        MyFolderRadioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyFolderRadioBtnMouseClicked(evt);
            }
        });

        activeFolderRadioBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        activeFolderRadioBtn.setText("Active Folders");
        activeFolderRadioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activeFolderRadioBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nestedCaseMenuBarLayout = new javax.swing.GroupLayout(nestedCaseMenuBar);
        nestedCaseMenuBar.setLayout(nestedCaseMenuBarLayout);
        nestedCaseMenuBarLayout.setHorizontalGroup(
            nestedCaseMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nestedCaseMenuBarLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(nestedCaseMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nestedCaseMenuBarLayout.createSequentialGroup()
                        .addGroup(nestedCaseMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MyFolderRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(activeFolderRadioBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(nestedCaseMenuBarLayout.createSequentialGroup()
                        .addComponent(openNewCaseRadioBtn)
                        .addGap(15, 477, Short.MAX_VALUE))))
        );
        nestedCaseMenuBarLayout.setVerticalGroup(
            nestedCaseMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nestedCaseMenuBarLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(openNewCaseRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(MyFolderRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(activeFolderRadioBtn)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        nestedTabbedCase.addTab("", nestedCaseMenuBar);

        backJlabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        backJlabel.setText("Back");
        backJlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backJlabelMouseClicked(evt);
            }
        });

        clientIdjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clientIdjLabel.setText("Client ID");

        categoryjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        categoryjLabel.setText("Category");

        caseworkerjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        caseworkerjLabel.setText("Case Worker");

        introjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        introjLabel.setText("Introduced By");

        caseLocjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        caseLocjLabel.setText("Case Location");

        openingDatejLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        openingDatejLabel.setText("Opening Date");

        paymentjLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        paymentjLabel.setText("Payment ID");

        saveBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        openingDateChooser.setDateFormatString("yyyy-MM-dd");
        openingDateChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openingDateChooserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout openNewCaseJpanelLayout = new javax.swing.GroupLayout(openNewCaseJpanel);
        openNewCaseJpanel.setLayout(openNewCaseJpanelLayout);
        openNewCaseJpanelLayout.setHorizontalGroup(
            openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(categoryjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                .addComponent(clientIdjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(caseworkerjLabel)))
                    .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(introjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(caseLocjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paymentjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(openingDatejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBtn)
                        .addGap(156, 156, 156))
                    .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                        .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(paymentTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientIdTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(introTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caseLocTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caseWorkerTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openingDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(openingDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)))
                .addComponent(backJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        openNewCaseJpanelLayout.setVerticalGroup(
            openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openNewCaseJpanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientIdjLabel)
                    .addComponent(clientIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryjLabel)
                    .addComponent(categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseworkerjLabel)
                    .addComponent(caseWorkerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(introjLabel)
                    .addComponent(introTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caseLocjLabel)
                    .addComponent(caseLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openingDatejLabel)
                            .addComponent(openingDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(openNewCaseJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(paymentjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(saveBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openNewCaseJpanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(openNewCaseJpanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(openingDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        nestedTabbedCase.addTab("tab2", openNewCaseJpanel);

        javax.swing.GroupLayout tab_caseFolderLayout = new javax.swing.GroupLayout(tab_caseFolder);
        tab_caseFolder.setLayout(tab_caseFolderLayout);
        tab_caseFolderLayout.setHorizontalGroup(
            tab_caseFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_caseFolderLayout.createSequentialGroup()
                .addGroup(tab_caseFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_caseFolderLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel15))
                    .addGroup(tab_caseFolderLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(nestedTabbedCase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        tab_caseFolderLayout.setVerticalGroup(
            tab_caseFolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_caseFolderLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nestedTabbedCase, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        nestedTabbedCase.getAccessibleContext().setAccessibleName("");

        tab_container.addTab("tab3", tab_caseFolder);

        tab_accounts.setBackground(new java.awt.Color(153, 0, 153));

        jLabel16.setText("jLabel6");

        javax.swing.GroupLayout tab_accountsLayout = new javax.swing.GroupLayout(tab_accounts);
        tab_accounts.setLayout(tab_accountsLayout);
        tab_accountsLayout.setHorizontalGroup(
            tab_accountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_accountsLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel16)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        tab_accountsLayout.setVerticalGroup(
            tab_accountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_accountsLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel16)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tab_container.addTab("tab3", tab_accounts);

        tab_communication.setBackground(new java.awt.Color(153, 0, 255));

        jLabel17.setText("jLabel6");

        javax.swing.GroupLayout tab_communicationLayout = new javax.swing.GroupLayout(tab_communication);
        tab_communication.setLayout(tab_communicationLayout);
        tab_communicationLayout.setHorizontalGroup(
            tab_communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_communicationLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel17)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        tab_communicationLayout.setVerticalGroup(
            tab_communicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_communicationLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel17)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tab_container.addTab("tab3", tab_communication);

        tab_settings.setBackground(new java.awt.Color(102, 102, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lawyer_ID", "First_Name", "Last_Name", "Email", "Birth_Date", "Gender"
            }
        ));
        ScrollPane_user_list.setViewportView(jTable1);

        searchBox_userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBox_userNameKeyReleased(evt);
            }
        });

        title_searchBox_userName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        title_searchBox_userName.setText("Search");

        javax.swing.GroupLayout tab_settingsLayout = new javax.swing.GroupLayout(tab_settings);
        tab_settings.setLayout(tab_settingsLayout);
        tab_settingsLayout.setHorizontalGroup(
            tab_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_settingsLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(ScrollPane_user_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(tab_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_searchBox_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBox_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        tab_settingsLayout.setVerticalGroup(
            tab_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_settingsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(title_searchBox_userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchBox_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollPane_user_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        tab_container.addTab("tab3", tab_settings);

        main_container.add(tab_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 790, 510));
        tab_container.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_dashboard_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dashboard_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(0);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_dashboard_menuMouseClicked

    private void label_appointment_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_appointment_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(1);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_appointment_menuMouseClicked

    private void label_dashboard_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dashboard_menuMousePressed
        // TODO add your handling code here:
//        jPanel7.setBackground(clickedColor);
//         jPanel8.setBackground(defaultColor);
//         jPanel9.setBackground(defaultColor);
        label_dashboard_menu.setForeground(white);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_dashboard_menuMousePressed

    private void label_appointment_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_appointment_menuMousePressed
        // TODO add your handling code here:
        label_appointment_menu.setForeground(white);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_appointment_menuMousePressed

    private void label_dashboard_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dashboard_menuMouseReleased
        // TODO add your handling code here:
        label_dashboard_menu.setForeground(defaultColor);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_dashboard_menuMouseReleased

    private void label_appointment_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_appointment_menuMouseReleased
        // TODO add your handling code here:
        label_appointment_menu.setForeground(defaultColor);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_appointment_menuMouseReleased

    private void logOut_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOut_buttonActionPerformed

    private void label_addressBook_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_addressBook_menuMouseReleased
        // TODO add your handling code here:
        label_addressBook_menu.setForeground(defaultColor);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_addressBook_menuMouseReleased

    private void label_addressBook_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_addressBook_menuMousePressed
        // TODO add your handling code here:
        label_addressBook_menu.setForeground(white);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_addressBook_menuMousePressed

    private void label_addressBook_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_addressBook_menuMouseClicked
        // TODO add your handling code here:

        tab_container.setSelectedIndex(2);
        jTable1.setVisible(false);

    }//GEN-LAST:event_label_addressBook_menuMouseClicked

    private void label_todoList_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_todoList_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(3);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_todoList_menuMouseClicked

    private void label_todoList_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_todoList_menuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_todoList_menuMousePressed

    private void label_todoList_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_todoList_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_todoList_menuMouseReleased

    private void label_communication_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_communication_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(6);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_communication_menuMouseClicked

    private void label_communication_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_communication_menuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_communication_menuMousePressed

    private void label_communication_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_communication_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_communication_menuMouseReleased

    private void label_caseFolder_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_caseFolder_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(4);

        jTable1.setVisible(false);
    }//GEN-LAST:event_label_caseFolder_menuMouseClicked

    private void label_caseFolder_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_caseFolder_menuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_caseFolder_menuMousePressed

    private void label_caseFolder_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_caseFolder_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_caseFolder_menuMouseReleased

    private void label_account_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_account_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(5);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_account_menuMouseClicked

    private void label_account_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_account_menuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_account_menuMousePressed

    private void label_account_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_account_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_account_menuMouseReleased

    private void label_settings_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_settings_menuMouseClicked
        // TODO add your handling code here:

        tab_container.setEnabledAt(7, false);
        tab_container.setSelectedIndex(7);

        colorObject.hexToRGB();
        Color tableColor = new Color(colorObject.r1, colorObject.g1, colorObject.b1);
        // storedUserLabel.setVisible(false);
        jTable1.setVisible(true);
        jTable1.setBackground(tableColor);
        jTable1.setOpaque(false);

        try {
            connection = DriverManager.getConnection(databaseUrl, "sa", "123456");
            Statement st = connection.createStatement();
            String sql = "Select AdvocateId,FirstName,LastName,Email,PhoneNumber,DateOfBirth,Gender,Address_ From Advocate";
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                String SID = rs.getString("AdvocateId");
                String FirstName = rs.getString("FirstName");
                String LastName = rs.getString("LastName");
                String Email = rs.getString("Email");
                String phoneNumber = rs.getString("PhoneNumber");
                String BirthDate = rs.getString("DateOfBirth");
                String Gender = rs.getString("Gender");
                String address = rs.getString("Address_");
                String tbData[] = {SID, FirstName, LastName, Email, phoneNumber, BirthDate, Gender, address};
                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                tblModel.addRow(tbData);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_label_settings_menuMouseClicked

    private void label_settings_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_settings_menuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_settings_menuMousePressed

    private void label_settings_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_settings_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_settings_menuMouseReleased
    public void search(String str) {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        jTable1.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));

    }
    private void searchBox_userNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBox_userNameKeyReleased
        // TODO add your handling code here:

        //connection.close();
        String searchStr = searchBox_userName.getText();
        search(searchStr);

    }//GEN-LAST:event_searchBox_userNameKeyReleased

    private void openNewCaseRadioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openNewCaseRadioBtnMouseClicked
        // TODO add your handling code here:
        if (openNewCaseRadioBtn.isSelected()) {
              this.openingDateTextField.setVisible(false);
            MyFolderRadioBtn.setSelected(false);
            activeFolderRadioBtn.setSelected(false);
            this.nestedTabbedCase.setSelectedIndex(1);
        }
        //  
    }//GEN-LAST:event_openNewCaseRadioBtnMouseClicked

    private void activeFolderRadioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeFolderRadioBtnMouseClicked
        // TODO add your handling code here:

        if (activeFolderRadioBtn.isSelected()) {
            MyFolderRadioBtn.setSelected(false);
            openNewCaseRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_activeFolderRadioBtnMouseClicked

    private void MyFolderRadioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyFolderRadioBtnMouseClicked
        // TODO add your handling code here:
        if (MyFolderRadioBtn.isSelected()) {
            openNewCaseRadioBtn.setSelected(false);
            activeFolderRadioBtn.setSelected(false);
    }//GEN-LAST:event_MyFolderRadioBtnMouseClicked
    }
    private void backJlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backJlabelMouseClicked
        // TODO add your handling code here:
        this.nestedTabbedCase.setSelectedIndex(0);
    }//GEN-LAST:event_backJlabelMouseClicked
    public boolean nullCheck(ArrayList< String> s) {

        boolean val1 = false;
        for (int i = 0; i < s.size(); i++) {
            if (s.get(i).length() == 0) {
                val1 = true;
                break;
            }
        }
        return val1;
    }

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
          String selectdate = ((JTextField) openingDateChooser.getDateEditor().getUiComponent()).getText();
        openingDateTextField.setText(selectdate);
      
        String clientId = clientIdTextField.getText();
        String category = categoryTextField.getText();
        String caseWorker = caseWorkerTextField.getText();
        String Intro = introTextField.getText();
        String location = caseLocTextField.getText();
        String openingDate = openingDateTextField.getText();
        String paymentId = paymentTextField.getText();

        ArrayList< String> stList = new ArrayList<>();
    
        stList.add(clientId);
        stList.add(category);
        stList.add(caseWorker);
        stList.add(Intro);
        stList.add(location);
        stList.add(openingDate);
        stList.add(paymentId);

        boolean checkNull = nullCheck(stList);
        int flag = 0;
        String insertQuery = "INSERT into Cases (ClientId,Category,CaseWorker,IntroducedBy,CaseLocation,OpeningDate,PaymentId) Values"
                + " ( '" + clientId + "','" + category + "','" + caseWorker + "','" + Intro + "','" + location + "','" + openingDate + "','" + paymentId + "' )";

        if (checkNull == true) {
            JOptionPane.showMessageDialog(null, "Fill up the required fields information.", "Swing Tester", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            flag = 1;
        }
        
        try {
            connection = DriverManager.getConnection(databaseUrl, "sa", AdminPassword);
            st = connection.createStatement();
            
           if(flag == 1)
           {
               st.executeUpdate(insertQuery);
           }

        } catch (SQLException ex) {
            
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void openingDateChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openingDateChooserMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_openingDateChooserMouseClicked

    /**
     * @param args the command line arguments
     */
    public MainDashboard(String title) throws HeadlessException {

        super(title);
        storedUserLabel.setText("Hello," + title);
        //    System.out.println(title);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        MainDashboard phObject = new MainDashboard();
        phObject.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton MyFolderRadioBtn;
    private javax.swing.JPanel Panel_AddressBook_menu;
    private javax.swing.JPanel Panel_Appointment_menu;
    private javax.swing.JPanel Panel_account_menu;
    private javax.swing.JPanel Panel_caseFolder_menu;
    private javax.swing.JPanel Panel_communication_menu;
    private javax.swing.JPanel Panel_dashbord_menu;
    private javax.swing.JPanel Panel_setting_menu;
    private javax.swing.JPanel Panel_toDoList_menu;
    private javax.swing.JScrollPane ScrollPane_user_list;
    private javax.swing.JRadioButton activeFolderRadioBtn;
    private javax.swing.JLabel backJlabel;
    private javax.swing.JTextField caseLocTextField;
    private javax.swing.JLabel caseLocjLabel;
    private javax.swing.JTextField caseWorkerTextField;
    private javax.swing.JLabel caseworkerjLabel;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JLabel categoryjLabel;
    private javax.swing.JTextField clientIdTextField;
    private javax.swing.JLabel clientIdjLabel;
    private javax.swing.JPanel header_container;
    private javax.swing.JTextField introTextField;
    private javax.swing.JLabel introjLabel;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel21;
    private static javax.swing.JTable jTable1;
    private javax.swing.JLabel label_account_menu;
    private javax.swing.JLabel label_addressBook_menu;
    private javax.swing.JLabel label_appointment_menu;
    private javax.swing.JLabel label_caseFolder_menu;
    private javax.swing.JLabel label_communication_menu;
    private javax.swing.JLabel label_dashboard_menu;
    private javax.swing.JLabel label_settings_menu;
    private javax.swing.JLabel label_todoList_menu;
    private javax.swing.JButton logOut_button;
    private javax.swing.JPanel main_container;
    private javax.swing.JPanel menu_container;
    private javax.swing.JPanel nestedCaseMenuBar;
    private javax.swing.JTabbedPane nestedTabbedCase;
    private javax.swing.JPanel openNewCaseJpanel;
    private javax.swing.JRadioButton openNewCaseRadioBtn;
    private com.toedter.calendar.JDateChooser openingDateChooser;
    private javax.swing.JTextField openingDateTextField;
    private javax.swing.JLabel openingDatejLabel;
    private javax.swing.JTextField paymentTextField;
    private javax.swing.JLabel paymentjLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField searchBox_userName;
    private javax.swing.JLabel software_name;
    private static javax.swing.JLabel storedUserLabel;
    private javax.swing.JPanel tab_accounts;
    private javax.swing.JPanel tab_address_book;
    private javax.swing.JPanel tab_appointment;
    private javax.swing.JPanel tab_caseFolder;
    private javax.swing.JPanel tab_communication;
    private javax.swing.JTabbedPane tab_container;
    private javax.swing.JPanel tab_dashboard;
    private javax.swing.JPanel tab_settings;
    private javax.swing.JPanel tab_todoList;
    private javax.swing.JLabel title_searchBox_userName;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables
}
