/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Advocate;

import java.sql.Statement;
import java.sql.Connection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import Colour.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author parve
 */
public class phase1 extends javax.swing.JFrame {

    /**
     * Creates new form phase1
     */
    LoginPage object = new LoginPage();
    DatabaseCredentials dbc_1 = new DatabaseCredentials();
    String databaseUrl = dbc_1.getDatabaseUrl();
    Connection connection = null;

    Color defaultColor, clickedColor, white;
    color colorObject = new color();

    public phase1() {
        initComponents();
        this.tab_container.setEnabledAt(7, false);

        defaultColor = new Color(255, 204, 0);
        clickedColor = new Color(51, 51, 51);
        white = new Color(255, 255, 255);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_container = new javax.swing.JPanel();
        header_container = new javax.swing.JPanel();
        software_name = new javax.swing.JLabel();
        user_name = new javax.swing.JLabel();
        logOut_button = new javax.swing.JButton();
        menu_container = new javax.swing.JPanel();
        Panel_dashbord_menu = new javax.swing.JPanel();
        label_dashboard_menu = new javax.swing.JLabel();
        Panel_AddressBook_menu = new javax.swing.JPanel();
        label_addressBook_menu = new javax.swing.JLabel();
        Panel_Appointment_menu = new javax.swing.JPanel();
        label_appointment_menu = new javax.swing.JLabel();
        Panel_toDoList_menu = new javax.swing.JPanel();
        label_todoList_menu = new javax.swing.JLabel();
        Panel_caseFolder_menu = new javax.swing.JPanel();
        label_caseFolder_menu = new javax.swing.JLabel();
        Panel_account_menu = new javax.swing.JPanel();
        label_account_menu = new javax.swing.JLabel();
        Panel_communication_menu = new javax.swing.JPanel();
        label_communication_menu = new javax.swing.JLabel();
        Panel_setting_menu = new javax.swing.JPanel();
        label_settings_menu = new javax.swing.JLabel();
        tab_container = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        storedUserLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        main_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header_container.setBackground(new java.awt.Color(0, 0, 0));

        software_name.setForeground(new java.awt.Color(255, 255, 255));
        software_name.setText("CASIAC");

        user_name.setBackground(new java.awt.Color(255, 255, 255));
        user_name.setForeground(new java.awt.Color(255, 255, 255));
        user_name.setText("SUPER ADMIN");

        logOut_button.setText("LOG OUT");
        logOut_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header_containerLayout = new javax.swing.GroupLayout(header_container);
        header_container.setLayout(header_containerLayout);
        header_containerLayout.setHorizontalGroup(
            header_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(software_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 664, Short.MAX_VALUE)
                .addComponent(user_name)
                .addGap(18, 18, 18)
                .addComponent(logOut_button)
                .addContainerGap())
        );
        header_containerLayout.setVerticalGroup(
            header_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(header_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(software_name)
                    .addComponent(user_name)
                    .addComponent(logOut_button))
                .addGap(445, 445, 445))
        );

        main_container.add(header_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 60));

        menu_container.setBackground(new java.awt.Color(255, 255, 102));

        Panel_dashbord_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_dashboard_menu.setBackground(new java.awt.Color(255, 255, 102));
        label_dashboard_menu.setText("Dashboard");
        label_dashboard_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_dashboard_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_dashboard_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_dashboard_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_dashbord_menuLayout = new javax.swing.GroupLayout(Panel_dashbord_menu);
        Panel_dashbord_menu.setLayout(Panel_dashbord_menuLayout);
        Panel_dashbord_menuLayout.setHorizontalGroup(
            Panel_dashbord_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dashbord_menuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label_dashboard_menu)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        Panel_dashbord_menuLayout.setVerticalGroup(
            Panel_dashbord_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dashbord_menuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label_dashboard_menu)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Panel_AddressBook_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_addressBook_menu.setText("Address Book");
        label_addressBook_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_addressBook_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_addressBook_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_addressBook_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_AddressBook_menuLayout = new javax.swing.GroupLayout(Panel_AddressBook_menu);
        Panel_AddressBook_menu.setLayout(Panel_AddressBook_menuLayout);
        Panel_AddressBook_menuLayout.setHorizontalGroup(
            Panel_AddressBook_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AddressBook_menuLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(label_addressBook_menu)
                .addGap(16, 16, 16))
        );
        Panel_AddressBook_menuLayout.setVerticalGroup(
            Panel_AddressBook_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_AddressBook_menuLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(label_addressBook_menu)
                .addContainerGap())
        );

        Panel_Appointment_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_appointment_menu.setText("Appointment");
        label_appointment_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_appointment_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_appointment_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_appointment_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_Appointment_menuLayout = new javax.swing.GroupLayout(Panel_Appointment_menu);
        Panel_Appointment_menu.setLayout(Panel_Appointment_menuLayout);
        Panel_Appointment_menuLayout.setHorizontalGroup(
            Panel_Appointment_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(Panel_Appointment_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_Appointment_menuLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(label_appointment_menu)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        Panel_Appointment_menuLayout.setVerticalGroup(
            Panel_Appointment_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(Panel_Appointment_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_Appointment_menuLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(label_appointment_menu)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        Panel_toDoList_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_todoList_menu.setText("To Do List");
        label_todoList_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_todoList_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_todoList_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_todoList_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_toDoList_menuLayout = new javax.swing.GroupLayout(Panel_toDoList_menu);
        Panel_toDoList_menu.setLayout(Panel_toDoList_menuLayout);
        Panel_toDoList_menuLayout.setHorizontalGroup(
            Panel_toDoList_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(Panel_toDoList_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_toDoList_menuLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(label_todoList_menu)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        Panel_toDoList_menuLayout.setVerticalGroup(
            Panel_toDoList_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(Panel_toDoList_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_toDoList_menuLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(label_todoList_menu)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        Panel_caseFolder_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_caseFolder_menu.setText("Case Folders");
        label_caseFolder_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_caseFolder_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_caseFolder_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_caseFolder_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_caseFolder_menuLayout = new javax.swing.GroupLayout(Panel_caseFolder_menu);
        Panel_caseFolder_menu.setLayout(Panel_caseFolder_menuLayout);
        Panel_caseFolder_menuLayout.setHorizontalGroup(
            Panel_caseFolder_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
            .addGroup(Panel_caseFolder_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_caseFolder_menuLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(label_caseFolder_menu)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        Panel_caseFolder_menuLayout.setVerticalGroup(
            Panel_caseFolder_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(Panel_caseFolder_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_caseFolder_menuLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(label_caseFolder_menu)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        Panel_account_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_account_menu.setText("Accounts");
        label_account_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_account_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_account_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_account_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_account_menuLayout = new javax.swing.GroupLayout(Panel_account_menu);
        Panel_account_menu.setLayout(Panel_account_menuLayout);
        Panel_account_menuLayout.setHorizontalGroup(
            Panel_account_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
            .addGroup(Panel_account_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_account_menuLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(label_account_menu)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        Panel_account_menuLayout.setVerticalGroup(
            Panel_account_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(Panel_account_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_account_menuLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(label_account_menu)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        Panel_communication_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_communication_menu.setText("Communication");
        label_communication_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_communication_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_communication_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_communication_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_communication_menuLayout = new javax.swing.GroupLayout(Panel_communication_menu);
        Panel_communication_menu.setLayout(Panel_communication_menuLayout);
        Panel_communication_menuLayout.setHorizontalGroup(
            Panel_communication_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(Panel_communication_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_communication_menuLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(label_communication_menu)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Panel_communication_menuLayout.setVerticalGroup(
            Panel_communication_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(Panel_communication_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_communication_menuLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(label_communication_menu)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        Panel_setting_menu.setBackground(new java.awt.Color(255, 255, 102));

        label_settings_menu.setText("Settings");
        label_settings_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_settings_menuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                label_settings_menuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                label_settings_menuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_setting_menuLayout = new javax.swing.GroupLayout(Panel_setting_menu);
        Panel_setting_menu.setLayout(Panel_setting_menuLayout);
        Panel_setting_menuLayout.setHorizontalGroup(
            Panel_setting_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
            .addGroup(Panel_setting_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_setting_menuLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(label_settings_menu)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        Panel_setting_menuLayout.setVerticalGroup(
            Panel_setting_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
            .addGroup(Panel_setting_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_setting_menuLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(label_settings_menu)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout menu_containerLayout = new javax.swing.GroupLayout(menu_container);
        menu_container.setLayout(menu_containerLayout);
        menu_containerLayout.setHorizontalGroup(
            menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Panel_dashbord_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_AddressBook_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_Appointment_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_toDoList_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_caseFolder_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Panel_communication_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Panel_setting_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu_containerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_account_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        menu_containerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Panel_AddressBook_menu, Panel_Appointment_menu, Panel_communication_menu, Panel_dashbord_menu, Panel_toDoList_menu});

        menu_containerLayout.setVerticalGroup(
            menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_dashbord_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_AddressBook_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Appointment_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_toDoList_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_caseFolder_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(Panel_communication_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_setting_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(menu_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_containerLayout.createSequentialGroup()
                    .addContainerGap(284, Short.MAX_VALUE)
                    .addComponent(Panel_account_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(142, 142, 142)))
        );

        menu_containerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Panel_AddressBook_menu, Panel_Appointment_menu, Panel_communication_menu, Panel_dashbord_menu, Panel_toDoList_menu});

        main_container.add(menu_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, 470));

        jPanel7.setBackground(new java.awt.Color(102, 255, 255));

        jPanel21.setBackground(new java.awt.Color(102, 102, 102));

        storedUserLabel.setBackground(new java.awt.Color(102, 102, 102));
        storedUserLabel.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        storedUserLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(storedUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(storedUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(555, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        tab_container.addTab("tab1", jPanel7);

        jPanel8.setBackground(new java.awt.Color(102, 255, 204));

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel5)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel5)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        tab_container.addTab("tab2", jPanel8);

        jPanel9.setBackground(new java.awt.Color(204, 0, 102));

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel6)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel6)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tab_container.addTab("tab3", jPanel9);

        jPanel16.setBackground(new java.awt.Color(204, 204, 0));

        jLabel14.setText("jLabel6");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel14)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel14)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tab_container.addTab("tab3", jPanel16);

        jPanel17.setBackground(new java.awt.Color(0, 51, 51));

        jLabel15.setText("jLabel6");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel15)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel15)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tab_container.addTab("tab3", jPanel17);

        jPanel18.setBackground(new java.awt.Color(153, 0, 153));

        jLabel16.setText("jLabel6");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel16)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel16)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tab_container.addTab("tab3", jPanel18);

        jPanel19.setBackground(new java.awt.Color(153, 0, 255));

        jLabel17.setText("jLabel6");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel17)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel17)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tab_container.addTab("tab3", jPanel19);

        jPanel20.setBackground(new java.awt.Color(102, 102, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lawyer_ID", "First_Name", "Last_Name", "Email", "Birth_Date", "Gender"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Search");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        tab_container.addTab("tab3", jPanel20);

        main_container.add(tab_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 790, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_dashboard_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dashboard_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(0);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_dashboard_menuMouseClicked

    private void label_appointment_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_appointment_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(1);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_appointment_menuMouseClicked

    private void label_dashboard_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dashboard_menuMousePressed
        // TODO add your handling code here:
//        jPanel7.setBackground(clickedColor);
//         jPanel8.setBackground(defaultColor);
//         jPanel9.setBackground(defaultColor);
        label_dashboard_menu.setForeground(white);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_dashboard_menuMousePressed

    private void label_appointment_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_appointment_menuMousePressed
        // TODO add your handling code here:
        label_appointment_menu.setForeground(white);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_appointment_menuMousePressed

    private void label_dashboard_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dashboard_menuMouseReleased
        // TODO add your handling code here:
        label_dashboard_menu.setForeground(defaultColor);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_dashboard_menuMouseReleased

    private void label_appointment_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_appointment_menuMouseReleased
        // TODO add your handling code here:
        label_appointment_menu.setForeground(defaultColor);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_appointment_menuMouseReleased

    private void logOut_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOut_buttonActionPerformed

    private void label_addressBook_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_addressBook_menuMouseReleased
        // TODO add your handling code here:
        label_addressBook_menu.setForeground(defaultColor);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_addressBook_menuMouseReleased

    private void label_addressBook_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_addressBook_menuMousePressed
        // TODO add your handling code here:
        label_addressBook_menu.setForeground(white);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_addressBook_menuMousePressed

    private void label_addressBook_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_addressBook_menuMouseClicked
        // TODO add your handling code here:

        tab_container.setSelectedIndex(2);
        jTable1.setVisible(false);

    }//GEN-LAST:event_label_addressBook_menuMouseClicked

    private void label_todoList_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_todoList_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(3);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_todoList_menuMouseClicked

    private void label_todoList_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_todoList_menuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_todoList_menuMousePressed

    private void label_todoList_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_todoList_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_todoList_menuMouseReleased

    private void label_communication_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_communication_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(6);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_communication_menuMouseClicked

    private void label_communication_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_communication_menuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_communication_menuMousePressed

    private void label_communication_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_communication_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_communication_menuMouseReleased

    private void label_caseFolder_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_caseFolder_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(4);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_caseFolder_menuMouseClicked

    private void label_caseFolder_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_caseFolder_menuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_caseFolder_menuMousePressed

    private void label_caseFolder_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_caseFolder_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_caseFolder_menuMouseReleased

    private void label_account_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_account_menuMouseClicked
        // TODO add your handling code here:
        tab_container.setSelectedIndex(5);
        jTable1.setVisible(false);
    }//GEN-LAST:event_label_account_menuMouseClicked

    private void label_account_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_account_menuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_account_menuMousePressed

    private void label_account_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_account_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_account_menuMouseReleased

    private void label_settings_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_settings_menuMouseClicked
        // TODO add your handling code here:

        tab_container.setEnabledAt(7, false);
        tab_container.setSelectedIndex(7);

colorObject.hexToRGB();
Color tableColor = new Color(colorObject.r1,colorObject.g1,colorObject.b1);
        // storedUserLabel.setVisible(false);
          jTable1.setVisible(true);
        jTable1.setBackground(tableColor);
        jTable1.setOpaque(false);
               
       try {
            connection = DriverManager.getConnection(databaseUrl);
            Statement st = connection.createStatement();
            String sql = "Select LawyerId,LFName,LLName,LEmail,LPhone,LDate,LGender From Advocate";

            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String SID = rs.getString("LawyerId");
                String FirstName = rs.getString("LFName");
                String LastName = rs.getString("LLName");
                String Email = rs.getString("LEmail");
                String phoneNumber = rs.getString("LPhone");
                String BirthDate = rs.getString("LDate");
                String Gender = rs.getString("LGender");
                String tbData[] = {SID, FirstName, LastName, Email, phoneNumber, BirthDate, Gender};
                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
                tblModel.addRow(tbData);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_label_settings_menuMouseClicked

    private void label_settings_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_settings_menuMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_settings_menuMousePressed

    private void label_settings_menuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_settings_menuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_label_settings_menuMouseReleased
public void search(String str){
 
  DefaultTableModel   model = (DefaultTableModel) jTable1.getModel();
         TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
         jTable1.setRowSorter(trs);
         trs.setRowFilter(RowFilter.regexFilter(str));

}
    private void searchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyReleased
                    // TODO add your handling code here:
            
                    //connection.close();
                 
            String searchStr = searchTextField.getText();
            search(searchStr);
        
    }//GEN-LAST:event_searchTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public phase1(String title) throws HeadlessException {

        super(title);
        storedUserLabel.setText("Hello," + title);
        //    System.out.println(title);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(phase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(phase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(phase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(phase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        phase1 phObject = new phase1();
        phObject.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_AddressBook_menu;
    private javax.swing.JPanel Panel_Appointment_menu;
    private javax.swing.JPanel Panel_account_menu;
    private javax.swing.JPanel Panel_caseFolder_menu;
    private javax.swing.JPanel Panel_communication_menu;
    private javax.swing.JPanel Panel_dashbord_menu;
    private javax.swing.JPanel Panel_setting_menu;
    private javax.swing.JPanel Panel_toDoList_menu;
    private javax.swing.JPanel header_container;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JLabel label_account_menu;
    private javax.swing.JLabel label_addressBook_menu;
    private javax.swing.JLabel label_appointment_menu;
    private javax.swing.JLabel label_caseFolder_menu;
    private javax.swing.JLabel label_communication_menu;
    private javax.swing.JLabel label_dashboard_menu;
    private javax.swing.JLabel label_settings_menu;
    private javax.swing.JLabel label_todoList_menu;
    private javax.swing.JButton logOut_button;
    private javax.swing.JPanel main_container;
    private javax.swing.JPanel menu_container;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel software_name;
    private static javax.swing.JLabel storedUserLabel;
    private javax.swing.JTabbedPane tab_container;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables
}
