/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Advocate;

/**
 *
 * @author taral
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplashJpane1 = new javax.swing.JPanel();
        SplashHeaderJlabel = new javax.swing.JLabel();
        splashProgressbar1 = new javax.swing.JProgressBar();
        Splash_imgLabel = new javax.swing.JLabel();
        SplashPercentageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        SplashJpane1.setBackground(new java.awt.Color(0, 0, 0));

        SplashHeaderJlabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        SplashHeaderJlabel.setForeground(new java.awt.Color(255, 255, 255));
        SplashHeaderJlabel.setText("CASE   MANAGER");

        Splash_imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Advocate/hammer.jpg"))); // NOI18N

        SplashPercentageLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SplashPercentageLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout SplashJpane1Layout = new javax.swing.GroupLayout(SplashJpane1);
        SplashJpane1.setLayout(SplashJpane1Layout);
        SplashJpane1Layout.setHorizontalGroup(
            SplashJpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashProgressbar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SplashJpane1Layout.createSequentialGroup()
                .addGroup(SplashJpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SplashJpane1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(SplashHeaderJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SplashJpane1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(Splash_imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashJpane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SplashPercentageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SplashJpane1Layout.setVerticalGroup(
            SplashJpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SplashJpane1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(SplashHeaderJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Splash_imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SplashPercentageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(splashProgressbar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplashJpane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplashJpane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SplashScreen splashObj = new SplashScreen();
        splashObj.setVisible(true);
        try{
            for(int i=0; i<=100; i++)
            {
                Thread.sleep(70);
                splashObj.splashProgressbar1.setValue(i);
                String s1 = String.valueOf(i);
                splashObj.SplashPercentageLabel.setText(s1+"%");
                              
            }
          
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        splashObj.dispose();
        LoginPage Obj = new LoginPage();
        Obj.setVisible(true);
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SplashHeaderJlabel;
    private javax.swing.JPanel SplashJpane1;
    private javax.swing.JLabel SplashPercentageLabel;
    private javax.swing.JLabel Splash_imgLabel;
    private javax.swing.JProgressBar splashProgressbar1;
    // End of variables declaration//GEN-END:variables
}
